name: Update Resume

on:
  schedule:
    - cron: "0 2 * * 0-6"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main site
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Checkout resume repo
        uses: actions/checkout@v4
        with:
          repository: shrimpram/resume
          ref: gh-pages
          path: resume
          token: ${{ github.token }}

      - name: Commit & push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add resume
          git commit -m "Update resume" || echo "No changes"
          git push
