name: Update Resume

on:
  schedule:
    - cron: "0 2 * * 0-6"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main site
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Checkout resume repo
        uses: actions/checkout@v4
        with:
          repository: shrimpram/resume
          ref: gh-pages
          path: resume-src-tmp
          token: ${{ secrets.RESUME_PAT }}

      - name: Copy resume to main repo
        run: cp resume-src-tmp/Shreeram-Modi-Resume.pdf ./

      - name: Clean up
        run: rm -r ./resume-src-tmp

      - name: Commit & push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Shreeram-Modi-Resume.pdf
          git commit -m "resume: update resume" || echo "No changes"
          git push
